// Copyright 2025 KI3
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: savt.proto

package savt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SavtIpc_Echo_FullMethodName       = "/savt.SavtIpc/Echo"
	SavtIpc_GetStatus_FullMethodName  = "/savt.SavtIpc/GetStatus"
	SavtIpc_Start_FullMethodName      = "/savt.SavtIpc/Start"
	SavtIpc_Kill_FullMethodName       = "/savt.SavtIpc/Kill"
	SavtIpc_ReadLog_FullMethodName    = "/savt.SavtIpc/ReadLog"
	SavtIpc_GetConfig_FullMethodName  = "/savt.SavtIpc/GetConfig"
	SavtIpc_SetConfig_FullMethodName  = "/savt.SavtIpc/SetConfig"
	SavtIpc_GetHistory_FullMethodName = "/savt.SavtIpc/GetHistory"
)

// SavtIpcClient is the client API for SavtIpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SavtIpcClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoRequest, error)
	GetStatus(ctx context.Context, in *JobIdRequest, opts ...grpc.CallOption) (*Job, error)
	Start(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Job, error)
	Kill(ctx context.Context, in *JobIdRequest, opts ...grpc.CallOption) (*Job, error)
	ReadLog(ctx context.Context, in *JobIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	GetConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Config, error)
	SetConfig(ctx context.Context, in *Config, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetHistory(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetHistoryResponse, error)
}

type savtIpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSavtIpcClient(cc grpc.ClientConnInterface) SavtIpcClient {
	return &savtIpcClient{cc}
}

func (c *savtIpcClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoRequest)
	err := c.cc.Invoke(ctx, SavtIpc_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savtIpcClient) GetStatus(ctx context.Context, in *JobIdRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, SavtIpc_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savtIpcClient) Start(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, SavtIpc_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savtIpcClient) Kill(ctx context.Context, in *JobIdRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, SavtIpc_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savtIpcClient) ReadLog(ctx context.Context, in *JobIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SavtIpc_ServiceDesc.Streams[0], SavtIpc_ReadLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JobIdRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SavtIpc_ReadLogClient = grpc.ServerStreamingClient[LogEntry]

func (c *savtIpcClient) GetConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Config, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Config)
	err := c.cc.Invoke(ctx, SavtIpc_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savtIpcClient) SetConfig(ctx context.Context, in *Config, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SavtIpc_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savtIpcClient) GetHistory(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, SavtIpc_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SavtIpcServer is the server API for SavtIpc service.
// All implementations must embed UnimplementedSavtIpcServer
// for forward compatibility.
type SavtIpcServer interface {
	Echo(context.Context, *EchoRequest) (*EchoRequest, error)
	GetStatus(context.Context, *JobIdRequest) (*Job, error)
	Start(context.Context, *emptypb.Empty) (*Job, error)
	Kill(context.Context, *JobIdRequest) (*Job, error)
	ReadLog(*JobIdRequest, grpc.ServerStreamingServer[LogEntry]) error
	GetConfig(context.Context, *emptypb.Empty) (*Config, error)
	SetConfig(context.Context, *Config) (*emptypb.Empty, error)
	GetHistory(context.Context, *emptypb.Empty) (*GetHistoryResponse, error)
	mustEmbedUnimplementedSavtIpcServer()
}

// UnimplementedSavtIpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSavtIpcServer struct{}

func (UnimplementedSavtIpcServer) Echo(context.Context, *EchoRequest) (*EchoRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedSavtIpcServer) GetStatus(context.Context, *JobIdRequest) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedSavtIpcServer) Start(context.Context, *emptypb.Empty) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedSavtIpcServer) Kill(context.Context, *JobIdRequest) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedSavtIpcServer) ReadLog(*JobIdRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Errorf(codes.Unimplemented, "method ReadLog not implemented")
}
func (UnimplementedSavtIpcServer) GetConfig(context.Context, *emptypb.Empty) (*Config, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedSavtIpcServer) SetConfig(context.Context, *Config) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedSavtIpcServer) GetHistory(context.Context, *emptypb.Empty) (*GetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedSavtIpcServer) mustEmbedUnimplementedSavtIpcServer() {}
func (UnimplementedSavtIpcServer) testEmbeddedByValue()                 {}

// UnsafeSavtIpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SavtIpcServer will
// result in compilation errors.
type UnsafeSavtIpcServer interface {
	mustEmbedUnimplementedSavtIpcServer()
}

func RegisterSavtIpcServer(s grpc.ServiceRegistrar, srv SavtIpcServer) {
	// If the following call pancis, it indicates UnimplementedSavtIpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SavtIpc_ServiceDesc, srv)
}

func _SavtIpc_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavtIpcServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavtIpc_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavtIpcServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavtIpc_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavtIpcServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavtIpc_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavtIpcServer).GetStatus(ctx, req.(*JobIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavtIpc_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavtIpcServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavtIpc_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavtIpcServer).Start(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavtIpc_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavtIpcServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavtIpc_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavtIpcServer).Kill(ctx, req.(*JobIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavtIpc_ReadLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobIdRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SavtIpcServer).ReadLog(m, &grpc.GenericServerStream[JobIdRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SavtIpc_ReadLogServer = grpc.ServerStreamingServer[LogEntry]

func _SavtIpc_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavtIpcServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavtIpc_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavtIpcServer).GetConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavtIpc_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Config)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavtIpcServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavtIpc_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavtIpcServer).SetConfig(ctx, req.(*Config))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavtIpc_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavtIpcServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavtIpc_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavtIpcServer).GetHistory(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SavtIpc_ServiceDesc is the grpc.ServiceDesc for SavtIpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SavtIpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "savt.SavtIpc",
	HandlerType: (*SavtIpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _SavtIpc_Echo_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _SavtIpc_GetStatus_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _SavtIpc_Start_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _SavtIpc_Kill_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _SavtIpc_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _SavtIpc_SetConfig_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _SavtIpc_GetHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadLog",
			Handler:       _SavtIpc_ReadLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "savt.proto",
}
